image: docker:latest
services:
  - docker:dind

stages:
  - build
  - production

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ravepro/api .
    - docker push registry.gitlab.com/ravepro/api:latest
  only:
    - master

production:
  stage: production
  script:
    - echo "deploy to production!"
  only:
    - master
