proxy:
  image: sygeman/ravepro-proxy
  command: "nginx -g 'daemon off;'"
  links:
    - "client"
    - "api"
  ports:
    - "443:443"

client:
  image: sygeman/client
  environment:
    SC_CLIENT_ID: d03bc67acf78cf6f304edecde8cfc48c
  command: "nginx -g 'daemon off;'"

api:
  image: sygeman/api
  links:
    - "redis"
    - "postgres"
    - "mongo"
  environment:      
    CHAT_SECRET: 0293g02j39g023gn23
    TOKEN_SECRET: j9f84923vsndv821
    AUTH_KEY_SECRET: weojf9230j0923jr023
    SESSION_SECRET: f092m0f93j093n1-nfg023

    GOOGLE_CLIENT_ID: "146472258192-mio4jc9tvoku8a7efnimou72du9c7lqd.apps.googleusercontent.com"
    GOOGLE_SECRET: "xu8K3cB1gsISX2unhSXYmvhy"
    GOOGLE_CALLBACK_URL: "https://auth.rave.pro/authend/google"
    VK_CLIENT_ID: "5631679"
    VK_SECRET: "CLN5xTCfBR6YEmiCL6tU"
    VK_CALLBACK_URL: "https://auth.rave.pro/authend/vk"
    TWITCH_CLIENT_ID: "avhx1aans0aug8dbe9i1ns2717zyty"
    TWITCH_SECRET: "bbajfmzjxets9x2fsyo7hp1o6psgj8"
    TWITCH_CALLBACK_URL: "https://auth.rave.pro/authend/twitch"

    REDIS_URL: "redis://redis:6379"
    POSTGRES_USERNAME: "postgres"
    POSTGRES_DB: "ravepro"
    MONGO_URL: "mongodb://mongo/ravepro"
  command: yarn start

redis:
  image: "redis"

postgres:
  image: "postgres"
  environment:
    - POSTGRES_DB=ravepro

mongo:
  image: "mongo"