version: '3'
services:

  proxy:
    image: nginx:alpine
    logging:
      driver: none
    depends_on:
      - "client"
      - "api"
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf

  client:
    build: 
      context: ../../client
      dockerfile: Dockerfile-dev
    volumes:
      - ../../client:/src
      - /src/node_modules
    ports:
      - "3020:3020"

  api:
    build: 
      context: ../
      dockerfile: Dockerfile-dev
    depends_on:
      - "redis"
      - "postgres"
      - "mongo"
      - "nats"
    links:
      - "nats"
    environment:
      SESSION_SECRET: f092m0f93j093n1-nfg023
      BASE_URL: "http://localhost/"
      AUTH_URL: "http://localhost/"
      COOKIE_DOMAIN: "localhost"

      GOOGLE_CLIENT_ID: "146472258192-mio4jc9tvoku8a7efnimou72du9c7lqd.apps.googleusercontent.com"
      GOOGLE_SECRET: "xu8K3cB1gsISX2unhSXYmvhy"
      VK_CLIENT_ID: "5631679"
      VK_SECRET: "CLN5xTCfBR6YEmiCL6tU"
      TWITCH_CLIENT_ID: "sakl7zvgcbpy2hyg28vdj2g9v8ybyi"
      TWITCH_SECRET: "kggsonhfxe74efkfuhx8n71nfjdpzq"
      XSOLLA_SECRET: "PL0OeJtrEIN2HAVd"

      YT_KEY: "AIzaSyD3hVAg2TV7rrtBC7Rw4oxy_js-rAYx74M"
      SC_KEY: "d03bc67acf78cf6f304edecde8cfc48c"

      REDIS_URL: "redis://redis:6379"
      POSTGRES_URL: "postgresql://postgres:123@postgres/ravepro"
      MONGO_URL: "mongodb://mongo/ravepro"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: "redis"
    ports:
      - "6379:6379"
  
  sestorage:
    image: "redis"
  
  nats:
    image: "nats"
  
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=ravepro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"